2019-04-08 04:36:58,326 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/18Guide/app/__init__.py:44]
2019-04-30 22:19:32,725 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/18Guide/app/__init__.py:44]
2019-04-30 22:19:41,649 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/18Guide/app/__init__.py:44]
2019-08-30 11:20:19,683 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 11:23:41,735 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 15:27:59,785 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 15:40:49,356 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 15:42:16,216 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 15:43:06,355 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 15:43:18,739 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 15:43:37,696 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-30 16:21:04,322 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-08-31 18:57:45,416 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-09-01 07:13:16,063 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-09-01 08:29:35,792 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-09-01 08:34:15,304 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:44]
2019-09-01 08:34:30,097 ERROR: Exception on /register [POST] [in /home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/app/routes.py", line 48, in register
    db.session.commit()
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/bmackie/pythonDevelopment/flaskMegaTut/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: INSERT INTO user (username, email, password_hash, about_me, last_seen) VALUES (?, ?, ?, ?, ?)]
[parameters: ('beam', 'beam@foo.com', 'pbkdf2:sha256:150000$zcHY3Izp$bcb1d3fe53fea4e89e0558a02888636d474ed152e5ae910c7563c229062cb3ac', None, '2019-09-01 12:34:30.097545')]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-09-01 08:39:25,548 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
2019-09-01 08:43:41,392 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
2019-09-01 10:47:38,597 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
2019-09-01 15:22:41,693 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
2019-09-02 10:35:42,815 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
2019-09-02 10:42:15,503 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
2019-09-03 10:47:13,499 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
2019-09-03 10:53:04,608 INFO: Microblog startup [in /home/bmackie/pythonDevelopment/flaskMegaTut/app/__init__.py:45]
